# Plugins
plugins:
  - jekyll-include-cache
  - jekyll-seo-tag
  - jemoji


# Theme
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"


# Site Settings
locale: "en-US"
title: "Joshua Soberg"
subtitle: "Android Software Engineer"
email: soberg.dev@pm.me
description: >-
  My personal website/blog, revolving around lessons that I've learned in my career as a software engineer.
tagline: "Joshua Soberg's website/blog, revolving around modern Android software development"
baseurl: ""
url: "https://joshuasoberg.com/"
repository: "https://github.com/jsoberg/jsoberg.github.io"
#masthead_title: " "
github_username:  jsoberg
# Enable Search
search: true
search_provider          : lunr
lunr:
  search_within_pages    : true
# Hide RSS Feed options
atom_feed:
  hide: true
# Parse all possible MD extensions
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
# Allow copy for code blocks
enable_copy_code_button: true
# Show future posts while drafting
future: true
# Set WPM for read time = to Medium's (according to https://mediumcourse.com/how-is-medium-article-read-time-calculated/)
words_per_minute: 265
# Include pages for tags/etc
include:
  - _pages


# Author
author:
  name: "Joshua Soberg"
  #location: "United States"
  avatar: "/assets/images/avatar.png"
  bio: >- 
    Hi! I'm Josh, an experienced software engineer passionate about building impactful Android applications. 
    I've worked on everything from P2P communication tools to complex, real-time live-streaming applications
     that serve millions of users. I'm excited to continue learning and share some of the lessons that I've 
     picked up on my journey.
  email: "soberg.dev@pm.me"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: https://github.com/jsoberg/"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/joshuasoberg/"
    - label: "Medium"
      icon: "fab fa-fw fa-medium"
      url: "https://medium.com/@jsoberg"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"

# SEO Related Entries
google-site-verification: "xr2jamH2PKIHI58mmJfbLEWpYICRlGuYlKiNcW0T1iQ"
social:
  name: Joshua Soberg
  links:
    - https://www.linkedin.com/in/joshuasoberg/
    - https://github.com/jsoberg
    - https://medium.com/@jsoberg

# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path>/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path>/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/


# Site Theme
defaults:
  # _posts
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
      author_profile: true
      read_time: true
      comments: false
      share: false
      related: false
      show_date: true
      toc: true
      toc_sticky: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/