# Plugins
plugins:
  - jekyll-include-cache
  - jemoji


# Theme
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"


# Site Settings
locale: "en-US"
title: "Joshua Soberg"
subtitle: "Android Software Engineer"
email: soberg.dev@pm.me
description: >-
  My personal website/blog, revolving around modern Android software development.
baseurl: ""
url: "https://jsoberg.github.io/"
repository: "https://github.com/jsoberg/jsoberg.github.io"
#masthead_title: " "
github_username:  jsoberg
# Enable Search
search: true
search_provider          : lunr
lunr:
  search_within_pages    : true
# Hide RSS Feed options
atom_feed:
  hide: true


# Author
author:
  name: "Joshua Soberg"
  #location: "United States"
  avatar: "/assets/images/avatar.png"
  bio: >- 
    Hi! I'm Josh, an experienced software engineer passionate about building impactful Android applications. 
    I've worked on everything from P2P communication tools to complex, real-time live-streaming applications
     that serve millions of users. I'm excited to continue learning and share some of the lessons that I've 
     picked up on my journey.
  email: "soberg.dev@pm.me"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: https://github.com/jsoberg/"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/joshuasoberg/"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"


# Post Theme
defaults:
  # _posts
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
      author_profile: true
      read_time: true
      comments: false
      share: false
      related: false
      show_date: true
      toc: true
      toc_sticky: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/