# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Plugins

plugins:
  - jekyll-include-cache


# Theme

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"


# Site Settings

locale: "en-US"
title: "Joshua Soberg"
subtitle: "Android Software Engineer"
email: soberg.dev@pm.me
description: >-
  Joshua Soberg's personal blog/portfolio website, revolving around modern Android software development.
baseurl: ""
url: "https://jsoberg.github.io/"
repository: "https://github.com/jsoberg/jsoberg.github.io"
#masthead_title: " "
github_username:  jsoberg
# Enable Search
search: true
search_provider          : lunr
lunr:
  search_within_pages    : true
# Hide RSS Feed options
atom_feed:
  hide: true


# Author

author:
  name: "Joshua Soberg"
  #location: "United States"
  avatar: "/assets/images/avatar.png"
  bio: >- 
    Android Software Engineer with 10+ years professional experience designing, 
    developing, and publishing large-scale software products.
  email: "soberg.dev@pm.me"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: https://github.com/jsoberg/"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/joshuasoberg/"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"


# Post Theme

defaults:
  # _posts
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
      author_profile: true
      read_time: true
      comments: false
      share: false
      related: false
      show_date: true
      toc: true
      toc_sticky: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
